# Generated by Django 5.2.5 on 2025-09-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
